### ISSUE TITLE
Feature: Full text search todo

### ISSUE THREAD

**Issue by Brad-Edwards** [KeplerOps/kuzu#307]
Imported from `kuzudb/kuzu#4564`
Original URL: https://github.com/kuzudb/kuzu/issues/4564
Original author: @acquamarin
Original created at: 2024-11-24T18:20:26Z
### API

C++

### Short term
- [x] Ser/deser index catalog.
- [x] Import/export database.
- [x] Support virtual tables.
- [x] Optimize the storage of stop-words, we may only need to store the stop-words table only once.
- [x] Support optional parameters in standalone call functions (e.g., stopwords, stem).
- [x] Support multi-statement queries in the testing framework.
- [x] Disallow users from dropping a property that has an index on it.
- [x] Optimize the 3rd vertex compute, We don't have to run the vertex compute on each terms node.Instead, we only have to set our frontier to the nodes in our map.

### Long term
- [ ] Support querying a subset of columns in `query_fts_index()`. 
- [ ] Support copy in manual transactions.
- [x] Disallow users from querying virtual tables/properties(long term) and helper functions/internal FTS functions.  
- [x] Optimize hash aggregation/distinct performance
- [x] Optimize the lookup of term keys in `queryFTS`, we can probably do primary key lookup in such cases.  
- [x] Single direction relationship table.

**Comment by Brad-Edwards** [comment]
Imported comment from `kuzudb/kuzu`
Original author: @hpvd
Original created at: 2025-08-19T08:00:18Z
Original URL: https://github.com/kuzudb/kuzu/issues/4564#issuecomment-3199675631
just a good overview what is possible and make sense in sqlite search:
https://medium.com/@johnidouglasmarangon/full-text-search-in-sqlite-a-practical-guide-80a69c3f42a4

**Comment by Brad-Edwards** [comment]
Imported comment from `kuzudb/kuzu`
Original author: @hpvd
Original created at: 2025-08-19T08:04:29Z
Original URL: https://github.com/kuzudb/kuzu/issues/4564#issuecomment-3199688500
besides this, what to you think of adding
- Synonyms. This is very helpful for example when working with abbreviations
